steps:
  # 1️⃣ Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/ca-filefixer', '.']

  # 2️⃣ Push the image to Google Container Registry (GCR)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/ca-filefixer']

  # 3️⃣ Deploy to Cloud Run with 256MB RAM
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'ca-filefixer'
      - '--image=gcr.io/$PROJECT_ID/ca-filefixer'
      - '--platform=managed'
      - '--region=us-central1'
      - '--allow-unauthenticated'
      - '--memory=256Mi'  # ✅ Limit RAM to 256MB
      - '--cpu=1'
      - '--timeout=300'
      - '--max-instances=3'

images:
  - 'gcr.io/$PROJECT_ID/ca-filefixer'

options:
  logging: CLOUD_LOGGING_ONLY  # ✅ Use Cloud Logging (no storage bucket needed)
