steps:
  # 1️⃣ Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/fastapi-app', '.']

  # 2️⃣ Push the image to Google Container Registry (GCR)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/fastapi-app']

  # 3️⃣ Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'fastapi-app'
      - '--image=gcr.io/$PROJECT_ID/fastapi-app'
      - '--platform=managed'
      - '--region=us-central1'
      - '--allow-unauthenticated'
      - '--memory=256Mi'
      - '--cpu=1'
      - '--timeout=300'
      - '--update-env-vars=PORT=8080'
      - '--max-instances=3'

images:
  - 'gcr.io/$PROJECT_ID/fastapi-app'
